### PR TITLE
Preparing for addition of headless (token based) serving

### LINKED ISSUE #40: [feedback wanted] retake experiment option?

### PR DESCRIPTION
**Pull request by vsoch**
This PR will close #40 and #39. Specifically, additions are the following:

 - `--headless` has been added as an option for start, meaning that the portal is closed off and tokens must be entered to participate. The experiments order is either preset with `--experiments` and `--no-randomize`, randomized (default) or filtered to a limited subset (`--experiments` without `--no-randomize`),
 - `expfactory logs` can be used inside the container to print out application logs. With `--tail` they are left open for viewing updates.
 - the interactive portal study identifier used to be an incrementing number. To be consistent with the ability to generate a token, the identifier is now an automatically generated 34 character string.
 - a development builder container is now available for use for easy testing of (unmerged) features like this one [here](https://hub.docker.com/r/vanessa/expfactory-builder-dev/).

To properly review, we need help! @earcanal, you can use the full functionality of this PR by creating a Dockerfile with the [development container](https://hub.docker.com/r/vanessa/expfactory-builder-dev/).

```
docker run -v /tmp/data:/data vanessa/expfactory-builder-dev build test-task tower-of-london breath-counting-task
```
and then build your container from that like before, and please be sure to test both filesystem and relational (sqlite) database types, along with the commands that are outlined in the new docs --> https://github.com/expfactory/expfactory/blob/headless/docs/pages/2-usage.md I've literally been working on this for 9.5 hours straight, so I'm going to take a break while you test. Let's check off the following:

- [x] confirmed working as expected for filesystem and relational databases
- [x] user management commands (generating, refreshing, etc. tokens) work as expected

When things look good I need to:

- [ ] tag Github repo with version 3.1
- [x] tag the current builder with version 3.0, and merge and tag this update.
- [ ] update expfactory on pypi

Thanks! I need to go for a run now... in the pitch black... lol

### CODE REVIEW

**Comment by earcanal** [comment]
# Summary

This is an **AWESOME PR**,  so anything that follows are tiny constructive criticisms!

* It's a bit confusing (and feels like a bit of a regression) that databases use auto-increment ids, where's filesystems use tokens.  I'm sure there's a good technical reason for this, but I suspect experimenters will hate this. 

# Build
    $ docker pull vanessa/expfactory-builder
    Using default tag: latest
    latest: Pulling from vanessa/expfactory-builder
    Digest: sha256:e94cb468f0993cd0a8208a5524f187df5ffc6b39390aceee43f9c9e9a000a68f
    Status: Image is up to date for vanessa/expfactory-builder:latest
    $ docker run -v /tmp/data:/data vanessa/expfactory-builder-dev build test-task tower-of-london breath-counting-task state-mindfulness-survey
    Expfactory Version: 3.1
    LOG Recipe written to /data/Dockerfile
    $ cd data
    $ docker build -t expfactory/experiments .
    [...]
    $ mkdir -p /tmp/test/data

# Test

All tests run by connecting Chrome to localhost after starting container.  I've ticked tests which are a **PASS** for me and raised potential **ISSUE**s.

## headed filesystem

   $ docker run -v /tmp/test/data:/scif/data -d -p 80:80 expfactory/experiments start

### Results

- [x] Tick all, select `Random`
    * Run 1: `test-experiment` presented first
    * Run 2: `tower-of-london` presented first
- [x] Tick `test-experiment`
    - [x] **ISSUE** Overwrites existing `31f78d8a-a3b8-4c35-936e-ecf34a7623c6/test-task-results.json`

## headed sqlite

   $ docker run -v /tmp/test/data:/scif/data -d -p 80:80 expfactory/experiments --studyid test --database sqlite start

### Results

- [x] Tick `test-experiment`
    - [x] Data written to `test.db`, `participant.id = 1`
- [x] Tick `test-experiment`
    - [x] Data written to `test.db`, `participant.id = 2`
- [x] **ISSUE** a bit confusing that `participant.id` is a token in the filesystem, but numeric in sqlite?

## headed `--experiments`

    $ docker run -v /tmp/test/data:/scif/data -d -p 80:80 expfactory/experiments --studyid test --experiments test-task --database sqlite start

### Results

- [x] `test-experiment` only experiment available
- [x] Tick `test-experiment`
    - [x] Data written to `test.db`, `participant.id = 3`

## headless filesystem

    sudo rm -rf /tmp/data
    docker run -v /tmp/data:/data vanessa/expfactory-builder-dev build test-task tower-of-london breath-counting-task state-mindfulness-survey
    docker build -t expfactory/experiments .
    cd /tmp/data
    docker build -t expfactory/experiments .
    docker rm a01a28d1fa036e45f2d28a72a763f45245f5c976a1795ed84a108bd9c8ed1086
    docker run -p 80:80 -d --name experiments -v /tmp/test/data:/scif/data expfactory/experiments --headless --experiments test-task,state-mindfulness-survey --no-randomize start
    docker exec experiments expfactory users --new 4

    DATABASE	TOKEN
    /scif/data/expfactory/8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d	8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d[active]
    /scif/data/expfactory/7cd74cb3-6b44-4e36-9be2-473379f9d636	7cd74cb3-6b44-4e36-9be2-473379f9d636[active]
    /scif/data/expfactory/0d1d1886-c2c5-46d1-829f-5712684852ed	0d1d1886-c2c5-46d1-829f-5712684852ed[active]
    /scif/data/expfactory/5ec4ebb0-fd06-4861-922f-59ecc5e16d9a	5ec4ebb0-fd06-4861-922f-59ecc5e16d9a[active]

### Use token

- [x] `[Return]` -> `[A valid token is required. Contact the experiment administrator if you believe this to be a mistake.] `
- [x] `8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d` is valid token
  - [x] `--headless`
  - [x] `-experiments test-task,state-mindfulness-survey --no-randomize` i.e. task run in correct order `test-task`,`state-mindfulness-survey`
  - [x] Data written to `8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d/{state-mindfulness-survey-results.json,test-task-results.json}
  - [x] **ISSUE** Can reuse token `8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d`

### Revoke token

    $ docker exec experiments expfactory users --revoke 8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d
    [revoking] 8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d --> /scif/data/expfactory/8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d_revoked
    $ docker exec experiments expfactory users --list
    /scif/data/expfactory/0d1d1886-c2c5-46d1-829f-5712684852ed	0d1d1886-c2c5-46d1-829f-5712684852ed[active]
    /scif/data/expfactory/31f78d8a-a3b8-4c35-936e-ecf34a7623c6	31f78d8a-a3b8-4c35-936e-ecf34a7623c6[active]
    /scif/data/expfactory/5ec4ebb0-fd06-4861-922f-59ecc5e16d9a	5ec4ebb0-fd06-4861-922f-59ecc5e16d9a[active]
    /scif/data/expfactory/7cd74cb3-6b44-4e36-9be2-473379f9d636	7cd74cb3-6b44-4e36-9be2-473379f9d636[active]
    /scif/data/expfactory/8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d_revoked	8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d[revoked]

- [x] `8a1f19fb-0e6f-4a6f-b1a4-c40e5920675d` -> `[A valid token is required. Contact the experiment administrator if you believe this to be a mistake.] `
- [ ] **ISSUE** Revoking a token automatically generates a new one (see above)?

**Comment by vsoch** [comment]
hey @earcanal just want to check in your notes you are pulling `expfactory-builder` but in the instruction I wrote above you need to pull `expfactory-builder-dev` - is that a typo?

**Comment by vsoch** [comment]
Okay let's chat about the issues!

## headed filesystem
>> **ISSUE** Overwrites existing 31f78d8a-a3b8-4c35-936e-ecf34a7623c6/test-task-results.json. If the participant finishes the entire protocol, this token would be changed to `31f78d8a-a3b8-4c35-936e-ecf34a7623c6_finished` and not able to use. Did you find different behavior, and if so, give me steps to reproduce?

## headed sqlite
>> **ISSUE** a bit confusing that participant.id is a token in the filesystem, but numeric in sqlite?
Yeah I thought so too, but how would you suggest fixing? If the participant id is a changing token in relational databases, that means that we query / lookup based on token, but when a new token is issued (and the old one overwritten) the experiments admin would need to keep track of that. Is your preference to completely ignore the database id and just use tokens (that change?)

>>  **ISSUE** Can reuse token 8a1f19fb-0e6f-4a6f-b1a4-c40e5920675
As long as a partiicpant isn't finished, you would be able to re-use (imagine you are a participant that starts a battery and comes back later). Was this after finishing, and did you see a status of finished?

>> **ISSUE** Revoking a token automatically generates a new one (see above)?
refreshing a token should generate a new one, but revoking keeps the same (but appends [revoked] so it can't be used. See your screen above.

**Comment by vsoch** [comment]
and my goodness! You worked really hard on this review! Thank you :cookie:

**Comment by earcanal** [comment]
Arg, not a typo, the _headed_ parts were tested using the wrong container.  You can see me build using  `vanessa/expfactory-builder-dev` before testing headless.

**Comment by earcanal** [comment]
The overwriting issue is resolved on retest with `vanessa/expfactory-builder-dev`.  Running a second time generates data under a new token (directory) name.

**Comment by vsoch** [comment]
>> The overwriting issue is resolved on retest with vanessa/expfactory-builder-dev. Running a second time generates data under a new token (directory) name.

Yes that should be the case! Under regular (not headless) anyone can participate that goes to the portal, so the new token is generated.

**Comment by earcanal** [comment]
So the revoking "issue" above is expected behaviour.  In which case that's resolved.

**Comment by vsoch** [comment]
@earcanal let me know when this passes your remaining criteria above! And I can address any still outstanding issues.

**Comment by earcanal** [comment]
FYI, I just discovered `docker image ls`, and wrote this to clean containers and images

`docker ps -a | grep <image_id> | awk '{print $1}' | xargs docker rm && docker rmi <image_id>`

**Comment by vsoch** [comment]
that's some impressive bash-fu!! I'll give it a try when I need to make sure my OS doesn't explode :)

**Comment by earcanal** [comment]
0
_/\_

**Comment by vsoch** [comment]
hey @earcanal ! I've added some very basic tests, specifically:

 - building the builder
 - generating a container from the builder with test task
 - starting the container
 - checking that curl returns a response
 - very basic tests for the client 

but circleCI is very limited in being able to execute commands to a container. I think for now we probably can do our best effort in these (somewhat manual) tests, and if you have tested to your satisfaction we can approve and merge and update with a new release. For things like the builder and the robots that I'm working on, my thinking is that those will be moved to their own respective repos so testing is a bit simpler. I don't want to let this PR turn into a larger monster than it already is. Let me know your thoughts!

**Comment by earcanal** [comment]
Nice! :)

**Pull request merged**
