### PR TITLE
Added lax cookie to remove browser warning.

### PR DESCRIPTION
**Pull request by AlvaroAguilera**
Please consider merging the following cookie samesite police to remove warning in the browser's javascript console.

### CODE REVIEW

**Comment by vsoch** [comment]
I'm reading that this is the default unless it's set otherwise:

> This is the default cookie value if SameSite has not been explicitly specified in recent browser versions (see the "SameSite: Defaults to Lax" feature in the Browser Compatibility).

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Can you please walk me through why this is necessary? And if we choose to set it, why is Lax the best (more secure) choice?

**Comment by AlvaroAguilera** [comment]
Hi Vanessa,

without that line the cookie is set with SameSite=None and that causes the browser warning. We have to either use "SameSite=lax" or "SameSite=None; Secure". I chose lax because that's the default but I'm no expert on this...

**Comment by vsoch** [comment]
I can see that a particular user would vary in terms of opinion on this - for some silencing a warning is not an optimal solution. My suggestion is to allow the user to customize via an environment variable, which can be set in the Dockerfile before build. So to proceed I would suggest the following:

Make the setting optional, with default to unset (going to the browser default) this means adding it to [defaults](https://github.com/expfactory/expfactory/blob/b27b7af9944fee40643337f9f77cee37fa74abb5/expfactory/defaults.py#L75) (with no default other than None) 
```python
SESSION_COOKIE_SAMESITE = getenv("EXPFACTORY_SESSION_COOKIE_SAMESITE", default=None)
```

and then referencing it in the settings.py, e.g.,

```python
app.config["SESSION_COOKIE_SAMESITE"] = SESSION_COOKIE_SAMESITE
```

Then update the docs (there is a table here https://expfactory.github.io/customize#environment-variables) to explain to the user how to set it (e.g. to Lax in the Dockerfile would look like):

```dockerfile
export EXPFACTORY_SESSION_COOKIE_SAMESITE="Lax"
```
Please also provide explanation of the implications of this option, and provide the others as well.

This is the most direct way to provide you a means to control this functionality without hard coding your preference for other users.

**Comment by AlvaroAguilera** [comment]
That's a good idea. However, I still think the default value shouldn't produce a warning. We should pick one of the two valid options per default and let users change it as needed, IMHO.

**Comment by vsoch** [comment]
Thank you for your opinion! My opinion is that silencing a warning by default is not optimal. It's better for the user to see it and decide to act on it.

**Comment by vsoch** [comment]
I'm happy to have more discussion on this if you want to bring in someone who is an expert in the space that can comment on best practices (someone that works on a browser or general web security).

**Comment by AlvaroAguilera** [comment]
There are probably a lot of warnings that we could turn on all across the code, but that doesn't help anyone. I was trying to debug a different issue and had to fix this first to be sure that the cookie was not being discarded by the browser and causing the problem... so for me the warning was more confusing than helpful. Just my two cents. Perhaps some security guy can give his opinion on this. I'll just respect your opinion since you are doing otherwise a good job here.

**Comment by vsoch** [comment]
Thanks I appreciate that. I'm definitely happy to have a discussion about best practices, but the hard part is finding someone who has that expertise (I do not). I hope the suggestion is an amenable approach that is a step in the right direction until we can do that.

**Comment by AlvaroAguilera** [comment]
Note that Experiment Factory is using an old version of Flask (1.0.2) which defaults SameSite to None because that was a valid option back then. Flash 2.0 defaults to Lax, so the warning will go away as soon as the software stack is updated.

**Comment by vsoch** [comment]
Oh neat! So I'd also be open to a PR to use an updated version of Flask, of course we'd need to take care to make sure that things that are deprecated are updated, etc.

**Comment by AlvaroAguilera** [comment]
Yes, let's do that :+1:

**Comment by vsoch** [comment]
Sounds good! Thanks @AlvaroAguilera.

**Comment by vsoch** [comment]
Flask will be updated to greater than 2.0 soon, so closing here. Thanks!

**Pull request closed without merging**
