### PR TITLE
Add/check data exists

### PR DESCRIPTION
**Pull request by vsoch**
**Description of the Pull Request (PR):**

This is a quick test to see if we can load existing data (and not duplicate done experiments).

**This fixes or addresses the following GitHub issues:**

- Ref: #166 

**Checkoff for all PRs:**

 - [x] I have read the [Guidelines for Contributing](https://github.com/expfactory/expfactory/blob/master/.github/CONTRIBUTING.md) and this PR conforms to the stated requirements.
 - [x] I have updated the [CHANGELOG](https://github.com/expfactory/expfactory/blob/master/CHANGELOG.md)

Attn: @expfactory-admin

### CODE REVIEW

**Comment by danieljwilson** [comment]
So for dummy data you just mean a subject folder with a subset of the experiments already completed?
e.g.
[_danieljwilson_testing.zip](https://github.com/expfactory/expfactory/files/9661457/_danieljwilson_testing.zip)

Or do you need something else/additional?

**Comment by vsoch** [comment]
I'd ideally like:

- a Dockerfile minimized to just a handful of experiments (2 ideally) - the data won't have meaning unless we have matched to a container with the same installed experiments!
- a subject folder with one experiment completed, one not
- the exact steps you take (after build) to create your users and run

**Comment by danieljwilson** [comment]
Sure...

Dockerfile
```docker
FROM quay.io/vanessa/expfactory-builder:base

########################################
# Configure
########################################

ENV EXPFACTORY_STUDY_ID expfactory
ENV EXPFACTORY_SERVER localhost
ENV EXPFACTORY_CONTAINER true
ENV EXPFACTORY_DATA /scif/data
ENV EXPFACTORY_DATABASE filesystem
ENV EXPFACTORY_HEADLESS false
ENV EXPFACTORY_BASE /scif/apps
ENV EXPFACTORY_EXPERIMENT_FIRST=sona-id-entry

COPY startscript.sh /startscript.sh
RUN chmod u+x /startscript.sh

WORKDIR /opt 
RUN git clone -b add/order-first-last https://github.com/expfactory/expfactory
WORKDIR expfactory 
RUN cp script/nginx.https.conf /etc/nginx/sites-enabled/default && \
    cp script/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /scif/data # saved data
RUN mkdir -p /scif/apps # experiments 
RUN mkdir -p /scif/logs # gunicorn logs 
RUN python3 -m pip install gunicorn
RUN cp expfactory/config_dummy.py expfactory/config.py && \
    chmod u+x /opt/expfactory/script/generate_key.sh && \
    /bin/bash /opt/expfactory/script/generate_key.sh /opt/expfactory/expfactory/config.py
RUN python3 setup.py install
RUN python3 -m pip install pyaml    pymysql psycopg2-binary
RUN apt-get clean          # tests, mysql,  postgres

########################################
# Experiments
########################################

LABEL EXPERIMENT_general-self-efficacy-survey /scif/apps/general-self-efficacy-survey
WORKDIR /scif/apps
RUN expfactory install https://github.com/expfactory-experiments/general-self-efficacy-survey

LABEL EXPERIMENT_grit-scale-survey /scif/apps/grit-scale-survey
WORKDIR /scif/apps
RUN expfactory install https://github.com/expfactory-experiments/grit-scale-survey



ENTRYPOINT ["/bin/bash", "/startscript.sh"]
EXPOSE 5000
EXPOSE 443
EXPOSE 80
```
Subject folder
> see previous reply

Steps after build:
1. Create users: `docker exec thesis_battery_sona expfactory users --new 100 >> run1_participants.tsv`
2. Run
```shell
#!/usr/bin/env bash

docker run --name thesis_battery_sona -d -p 80:80 -p 443:443 \
    -v /etc/ssl/certs:/etc/ssl/certs:ro \
    -v /etc/ssl/private:/etc/ssl/private:ro \
    -v $PWD:/scif/data \
    danieljwilson/thesis_battery_sona --headless start
```

**Comment by vsoch** [comment]
Why are you creating 100 new participants and giving me one subject folder?

**Comment by danieljwilson** [comment]
Ah, I created 100 participants for the study so just copied that code. I was giving you just my own subject folder as I also was taking part in the experiment as a tester. 

Should I have shared something different?

**Comment by vsoch** [comment]
And none of the dummy data experiments are the two you chose for your battery :(

**Comment by vsoch** [comment]
Just nevermind it will be faster for me to do the work. :/

**Comment by danieljwilson** [comment]
I thought that my subject file had general self efficacy (which was in the docker file)
and didn't have grit, which was the other experiment in the docker file?

Maybe I misunderstood - was trying to put one experiment that already existed (in the subject folder) in the docker file and one that did not?

**Comment by vsoch** [comment]
Don't mind me, I'm tired and a bit ornery. You gave me an example that was broken with several things to debug:

- the Dockerfile was configured for https (which I wouldn't have off the bat without extra work)
- you had a custom experiment prefix / id which I also had to discover and change
- your instructions were not complete and I had to fill in the lines
- the setting of the FIRST experiment variable without that experiment was also an error
- the experiments you gave me needed to be cleaned up to only the two.

Just for the future, when a maintainer devotes their entire evening to trying to help you (which now it's been about 5 hours) I think it would be very nice to offer to help, and hand it back only when you've tried and cannot. I offered the testing data to be nice, and I think minimally if that is offered, you might put together a comprehensive dummy case that reproduces your issue and you've tested it to work. Otherwise, I'm spending a lot of time over here debugging for you. And I forgo all the things I wanted to do tonight to help, and I didn't even get to the part of developing because I was debugging.

Sorry for complaining - I think you are probably under a lot of stress, and I think we can do better next time :) I'm too tired to finish this tonight, I'll try to make some time in the next few weeks.

**Comment by vsoch** [comment]
okay I just pushed myself through the example (now added here) and my final testing and debugging, and added your modified (simplified) example with instructions for a user to reproduce. I'm done for these two PRs - up to you to test and review @danieljwilson ! Good luck!

**Comment by danieljwilson** [comment]
Thank you so much @vsoch .

I totally take your points. I am genuinely sorry I made your job more difficult. I will try to be more attentive about qc-ing the things I share in the future. I was trying to respond quickly and haven't slept in a couple of days so I definitely am not at my sharpest.

**Comment by danieljwilson** [comment]
I really don't want to make your life more difficult - I am honestly amazed at the time and help you are providing.

**Comment by vsoch** [comment]
Thank you @danieljwilson - and I totally understand! I hope these work for you and you can get some sleep! I've been there too, although not recently - I sleep a LOT these days, haha. I'm guessing you are running experiments for graduate school? I can almost guarantee you that life gets better after that - you get such luxuries like a dishwasher, an income that is more reasonable, and less "impending doom" because frankly it's really a hard existence as a grad student. I will definitely try to help and support you however I can.

**Comment by danieljwilson** [comment]
Yes, I am indeed a graduate student finishing up my thesis work 😅
Running an experiment that all members of my thesis committee warned me was "maybe a bit too ambitious" and trying to prove them wrong (so far with limited success)

In any case, very nice to hear about life on the other side...

**Comment by danieljwilson** [comment]
So I tried it first with the same Docker file script from before (just with all the experiments).

I created using this code:
```shell
#!/usr/bin/env bash

docker run -v $HOME/thesis_battery_sona:/data \
    quay.io/vanessa/expfactory-builder \
    build \
    sona-id-entry \
    five-item-ambition-survey \
    boredom-proneness-scale-short-survey \
    brief-sensation-seeking-survey \
    competitiveness-index-revised-survey \
    dass-21 \
    future-time-perspective-survey \
    general-self-efficacy-survey \
    grit-scale-survey \
    life-orientation-test-revised-optimism-survey \
    maximizing-tendency-survey \
    mindful-attention-awareness-survey \
    need-for-cognition-and-faith-in-intuition-survey \
    perceived-stress-survey \
    positive-and-negative-affect-short-survey \
    propensity-to-plan-survey \
    brief-self-control-survey \
    trait-emotional-intelligence-short-survey \
    trait-hedonic-capacity-survey \
    trait-robustness-of-self-confidence-survey \
    secular-measure-of-work-ethic-survey \
    attention-network-task \
    bickel-titrator \
    cognitive-reflection-survey \
    emotion-regulation \
    go-nogo \
    holt-laury-survey \
    information-sampling-task \
    keep-track \
    plus-minus \
    probabilistic-selection \
    ravens \
    shift-task \
    simon \
    simple-reaction-time \
    stroop \
    tower-of-london \
    two-stage-decision \
    affective-conflict-resolution-task \
    berlin-numeracy-test \
    cognitive-estimation-test \
    effort-avoidance-task \
    jdm-classics \
    semantic-verbal-fluency \
    psychomotor-vigilance-test \
    k6-survey \
    leisure-time-activity-survey \
    rosenberg-self-esteem-survey \
    --input build/docker/Dockerfile.https
```
I edited the docker file that was created by commented out the following code:

```docker
ARG branch=master
ENV branch=master
```
Adding
`ENV EXPFACTORY_EXPERIMENT_FIRST=sona-id-entry`

And changing
`RUN git clone -b ${branch} https://github.com/expfactory/expfactory`
to
`RUN git clone -b add/order-first-last https://github.com/expfactory/expfactory`

When I entered my subject token it took me to the `sona-id-entry` experiment first (even though it was completed in my subject folder). I thought perhaps this was just a bug due to the fact that it was being forced to serve it first but then after completing that "experiment" I started to see other completed experiments repeated when I refreshed a number of times.

I then erased everything and redid all of the previous steps but without commenting out the lines
```docker
ARG branch=master
ENV branch=master
```
And leaving `RUN git clone -b ${branch} https://github.com/expfactory/expfactory` as is...
But still adding `ENV EXPFACTORY_EXPERIMENT_FIRST=sona-id-entry`

This **did not** serve the `sona-id-entry` experiment first but **did** repeat previous experiments that were completed in my subject data folder...
Including `sona-id-entry` - just later on.

Just reporting this - not expecting speedy fixes!

Right now, I am thinking that maybe as a SUPER hacky immediate fix for the moment (since only 10 people have completed tasks already) is to pull their data out of those folders and save it and then tell them which experiments they have already done and can just enter nonsense for and move on...and perhaps increase their payment since it will still take them extra time.

**Comment by vsoch** [comment]
You need to use the branch here, add/check-data-exists, and test without the order variable set. The changes are only in this branch.

**Comment by vsoch** [comment]
The example I added is a good place to start: https://github.com/expfactory/expfactory/blob/6135020df899f6e21f2cb8fb9a0a86b02dd6d4b7/examples/docker/existing-data/Dockerfile

**Comment by vsoch** [comment]
The branch here should work to fix your bug, but you have to install it in the container. :)

**Comment by vsoch** [comment]
And @danieljwilson if we want these additions to persist, we should try to get them reviewed and then released! It's much easier to maintain a released feature than all these separate feature branches (and we have found out!)

**Comment by danieljwilson** [comment]
Okay, I have that branch up and working  🤞

How can I help with the review/release process? I have never done anything like this before but would like to pitch in however I can.

Best,
Daniel

**Comment by vsoch** [comment]
It's mostly important that when you test it with your experiments (or dummy test cases) it works as you'd like. E.g., for the branch here checking that data exists, you'd want to reproduce what I did - to start an experiment with existing data folders and confirm that the data is found (and you as the participant don't have to repeat again).

For the second part of the PR here (the one it's based off of) that has the ability to hide the experiment names in the URL, there is also a corresponding example in examples/docker that is ready to be built and used - so you can build that container and test it - try changing the setting to use it /not use it, try headless / not headless, etc. The basic idea when testing new features is that you are trying to:

1. ensure they work as you'd expect
2. try to break them / test edge cases
3. ensure the original functionality still works

Usually we can automate a lot of this, but because expfactory is so UI driven I don't have a good way to test these things!

**Pull request merged**
