### PR TITLE
Update 1-generate.md

### PR DESCRIPTION
**Pull request by earcanal**
Describe how to run the same task multiple times.

**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Ref: #

**Checkoff for all PRs:**

 - [ ] I have read the [Guidelines for Contributing](https://github.com/expfactory/expfactory/blob/master/.github/CONTRIBUTING.md) and this PR conforms to the stated requirements.
 - [ ] I have updated the [CHANGELOG](https://github.com/expfactory/expfactory/blob/master/CHANGELOG.md)

Attn: @expfactory-admin

### CODE REVIEW

**Comment by vsoch** [comment]
Do you think that this is the best location to put this?

**Comment by vsoch** [comment]
hey @earcanal I just pushed some changes to your branch, I wanted to preview to see if the location was appropriate (I think it is) and also rephrase some of the sentences a bit (and add additional links). Take a look and let me know if my changes are good, and we can merge after!

**Comment by earcanal** [comment]
I think the location is OK, but you've twisted the use case a little.  The way I originally framed it was that you want to run the _same_ task (i.e. not two different versions of the ANT) multiple times, with a different task (that you hypothesise will have different effects on the ANT) in between.

Your twist is an additional (very useful!) use case of running the same task multiple times with different variables to make it operate differently.  I just wanted to capture the Dockerfile tweaking necessary to get the same task in multiple times.  Maybe include a sentence after the simpler use case pointing this out, and referring to the **Participant Variables" section?

**Comment by vsoch** [comment]
I don't understand what you mean by the "same task" but "with a different task" - can you better explain?

**Comment by vsoch** [comment]
ohh you mean a third unrelated task? So the variable isn't ANT1 or ANT2, but some task in between? I still don't totally follow, lol.

**Comment by earcanal** [comment]
* ANT (baseline)
* IF experimental EXPERIMENTAL-TASK else CONTROL-TASK
* ANT (post treatment)

Both ANTs need to be run the same way so you can compare post treatment to baseline.

**Comment by vsoch** [comment]
Understood! Tho first and last lines come down to copying and renaming the folder / exp_id (what I thought this change to the docs was mentioning). You want to add the additional logic for the second line? How are you currently doing this?

**Comment by earcanal** [comment]
I guess we could, although it opens the can of worms of [touching tasks so they understand `skip`](https://github.com/earcanal/attention-network-task/blob/master/index.html).  Once they do, I do it like this:

```
experimental-task,skip,1,control-token
control-task,skip,1,experimental-token
```

... and if we're explaining that, then we might as well go the whole way and recommend generating all the tokens require for your n in each group and configuring them in your variables file.  Then use your preferred randomisation method to dish them out.

**Comment by vsoch** [comment]
I'm not sure what this PR intends to explain then. I changed the description to describe what expfactory can now handle, and you are saying the changes are incorrect because you are describing a different use case.

**Comment by vsoch** [comment]
okay, I'm content with the changes (thus far) and please feel free to do another PR if/when the second (more advanced) use case has a solution.

**Comment by earcanal** [comment]
Looks good.

**Pull request merged**
