### PR TITLE
Updating psycog2 version, and automated builds

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

**Description of the Pull Request (PR):**

This will fix the version of psycog2 built in the expfactory containers, which is important as later versions are creating a bug:

```
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    warning: manifest_maker: standard file '-c' not found


    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7ddtwk2u/psycopg2/
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c python3 -m pip install pyaml    pymysql psycopg2' returned a non-zero code: 1
```

I'm also adding automated docker builds / push for all the containers - I have a script I ran locally but don't think this is appropriate for long term sustainability.

Attn: @expfactory-admin

### CODE REVIEW

**Comment by vsoch** [comment]
Finally successful build! Merging will test the deployment - if there is a bug I'll need to shell in and fix manually, and update the code, and it can be redone with push to master.

**Comment by vsoch** [comment]
Wow, it's a Pi release, on Pypi! https://pypi.org/project/expfactory/3.14/ AMAZING.

**Comment by earcanal** [comment]
You deserve a pie.

**Comment by vsoch** [comment]
I do deserve a pie. Someone should send me a pie!

**Comment by rwblair** [comment]
🥧

**Pull request merged**
